#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
test_flight_id                            : 

appstore_link                             : https://testflight.apple.com/join/Z02ONGZh                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Saving Jar                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Smart Expense Tracking                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Saving Jar helps you to keep track of your daily expenses.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Luca Beurer-Kellner                                
your_link                                 : 
your_city                                 : Zurich
email_address                             : lucabeurerkellner@gmail.com
facebook_username                         : 
instagram_username                        : 
twitter_username                          : lbeurerkellner
github_username                           : lbeurerkellner
youtube_username                          :

# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title                                 : Expense Tracking
    description                           : Enter your expenses using a simple and fast UI. Saving Jar automatically aggregates your expense data and shows you interesting visualisations of your spending habits.
    fontawesome_icon_name                 : money-bill-wave
    
  - title                                 : Smart Budget
    description                           : Based on your expense history, Saving Jar provides you with a daily budget recommendation such that you never exceed your overall budgeting goals.
    fontawesome_icon_name                 : magic 

  - title                                 : Import/Export
    description                           : All your expense data remains portable and can easily be imported and exported.
    fontawesome_icon_name                 : table



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               :                     # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
